# Generated by Django 5.1.4 on 2024-12-13 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='country',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='Only 3 characters are allowed.')]),
        ),
    ]
