# Generated by Django 5.1.4 on 2024-12-13 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_alter_traveler_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='country',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
