# Generated by Django 5.1.2 on 2024-10-27 12:16

import author.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='First name should contain only letters.', max_length=40, validators=[author.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Last name should contain only letters.', max_length=50, validators=[author.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', max_length=6, validators=[author.models.validate_passcode]),
        ),
    ]
